import {
  LuBadge,
  LuBriefcase,
  LuBuilding,
  LuContact,
  LuHeartHandshake,
  LuHelpingHand,
  LuHome,
  LuInfo,
  LuLayoutDashboard,
  LuMilestone,
  LuNewspaper,
  LuShield,
  LuStar,
  LuTarget,
  LuUsers,
  LuBus,
  LuCrown,
  LuGitPullRequest,
  LuMedal,
  LuGitBranch,
  LuBell,
  LuMail,
  LuBuilding2,
  LuUserCheck,
  LuImage,
  LuLogIn,
} from "react-icons/lu";

export const menus = [
  {
    name: "Dashboard",
    path: "/dashboard",
    icon: LuLayoutDashboard,
    roles: ["superadmin", "admin", "user"],
  },
  {
    name: "Home",
    path: "/home",
    icon: LuHome,
    roles: ["superadmin"],
  },
  {
    name: "Home",
    path: "/home-department",
    icon: LuHome,
    roles: ["admin", "user"],
  },
  {
    name: "Aboutus",
    path: "/aboutus",
    icon: LuInfo,
    roles: ["superadmin"],
  },
  {
    name: "Aboutus",
    path: "/aboutus-department",
    icon: LuInfo,
    roles: ["admin", "user"],
  },
    {
    name: "Banner",
    path: "/banners",
    icon: LuImage,
    roles: ["superadmin"],
  },
  {
    name: "Login URL",
    path: "/employeeLoginURL",
    icon: LuLogIn,
    roles: ["superadmin"],
  },
  {
    name: "Affiliates",
    path: "/affiliates",
    icon: LuHeartHandshake,
    roles: ["superadmin"],
  },
  {
    name: "Awards",
    path: "/awards",
    icon: LuMedal,
    roles: ["superadmin", "admin", "user"],
  },
  {
    name: "Brands",
    path: "/brands",
    icon: LuStar,
    roles: ["superadmin", "admin", "user"],
  },
  {
    name: "Careers",
    icon: LuBriefcase,
    roles: ["superadmin", "admin", "user"],
    submenu: [
      {
        name: "Careers Form",
        path: "/careers/careers-form",
        roles: ["superadmin", "admin", "user"],
      },
      {
        name: "Careers Opening",
        path: "/careers/careers-opening",
        roles: ["superadmin", "admin", "user"],
      },
    ],
  },
  { name: "Clients", path: "/clients", icon: LuUsers, roles: ["superadmin"] },
  {
    name: "Contact",
    icon: LuContact,
    roles: ["superadmin", "admin", "user"],
    submenu: [
      {
        name: "Contact Info",
        path: "/contact/contact-info",
        roles: ["superadmin"],
      },
      {
        name: "Contact Form",
        path: "/contact/contact-form",
        roles: ["superadmin", "user", "admin"],
      },
    ],
  },
  {
    name: "Core Business",
    path: "/core-business",
    icon: LuBuilding,
    roles: ["admin", "superadmin", "user"],
  },
  {
    name: "Equipments",
    icon: LuBus,
    roles: ["admin", "superadmin", "user"],
    submenu: [
      {
        name: "Equipments",
        path: "/equipments",
        roles: ["admin", "superadmin", "user"],
      },
      {
        name: "Equipments Category",
        path: "/equipments/category",
        roles: ["admin", "superadmin", "user"],
      },
    ],
  },
  // {
  //   name: "Event",
  //   path: "/event",
  //   icon: LuImage,
  //   roles: ["superadmin"],
  // },
  {
    name: "Facility",
    path: "/facility",
    icon: LuBuilding2,
    roles: ["admin", "superadmin", "user"],
  },
  {
    name: "MailingList",
    path: "/mailinglist",
    icon: LuMail,
    roles: ["superadmin"],
  },
  {
    name: "MailingList",
    path: "/mailinglist-department",
    icon: LuMail,
    roles: ["admin", "user"],
  },
  {
    name: "Milestones",
    path: "/milestones",
    icon: LuMilestone,
    roles: ["superadmin"],
  },
  {
    name: "Milestones",
    path: "/milestones-department",
    icon: LuMilestone,
    roles: ["admin", "user"],
  },
  {
    name: "News",
    icon: LuNewspaper,
    roles: ["superadmin", "admin", "user"],
    submenu: [
      { name: "CSR", path: "/news/csr", roles: ["superadmin"] },
      {
        name: "Image Gallery",
        path: "/news/image-gallery",
        roles: ["superadmin", "admin", "user"],
      },
      {
        name: "Latest News",
        path: "/news/latest-news",
        roles: ["superadmin", "admin", "user"],
      },
      {
        name: "Publication",
        path: "/news/publication",
        roles: ["superadmin", "admin", "user"],
      },
      {
        name: "Video Gallery",
        path: "/news/video-gallery",
        roles: ["superadmin", "admin", "user"],
      },
    ],
  },
  {
    name: "Notification",
    path: "/notification",
    icon: LuBell,
    roles: ["superadmin"],
  },
  {
    name: "Projects",
    path: "/projects",
    icon: LuTarget,
    roles: ["superadmin", "admin", "user"],
  },
  { name: "Qhse", path: "/qhse", icon: LuShield, roles: ["superadmin"] },
  {
    name: "Qualification",
    path: "/qualification",
    icon: LuBadge,
    roles: ["superadmin"],
  },
  {
    name: "Quotation",
    path: "/quotation",
    icon: LuGitPullRequest,
    roles: ["superadmin", "admin", "user"],
  },
  {
    name: "Regions",
    path: "/regions",
    icon: LuGitBranch,
    roles: ["superadmin"],
  },
  {
    name: "Roles",
    path: "/roles",
    icon: LuCrown,
    roles: ["superadmin", "admin"],
  },
  {
    name: "Service",
    path: "/service",
    icon: LuUserCheck,
    roles: ["admin", "superadmin", "user"],
  },
  {
    name: "Support Service",
    path: "/support-service",
    icon: LuHelpingHand,
    roles: ["superadmin"],
  },
];
